### ISSUE TITLE
crashing in Ardour

### ISSUE THREAD

**Issue by sandsound** [harryhaaren/openAV-Fabla2#44]
I get a lot of crashes in Ardour4 using he latest Fabla 2.0, whenever I try to open the ui.

truncated terminal output:
....
void Fabla2::Fabla2DSP::uiMessage(int, int, int, int, float) : sample not valid! Fix this.
The program 'ardour-4.7.0' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
....

Sorry if this is Ardour-related and not Fabla.

Love the new layout btw :-)

**Comment by harryhaaren** [comment]
@sandsound thanks for the report. I'm downloading the latest Ardour4 debug build now, and noted the possibility of the Gcc 4/5 breakage issue (see "Binary Interface" section of http://nightly.ardour.org/)

Did you build Ardour and Fabla2 yourself? Or are you using Gcc4 version of Ardour + Fabla2 built yourself with Gcc5?

Sorry to ask these nasty questions - but it is a possibility that this is the root cause. Thanks -Harry

**Comment by sandsound** [comment]
I'm using gcc 4.9.2 (Debian 4.9.2-10) to compile Fabla2. Ardour is just installed using the latest 4.7.0 64-bit installer downloaded from ardour.org, so I'm not sure how it is compiled.

I did have another issue that may be related.
When trying to load a saved song in Ardour, Fabla2 doesn't seam to find the right path to my samples and I get a series of:
Error Loading andie/ardour_music/fabla2_test/plugins/260/state2/hihat_8.wav-1.wav-1.wav-1.wav : Pad 14 : Sample 0 : Frames == 0, ignoring this sample! 

The full path to my samples is /home/sandie/ardour_music/drums/single_shot/ and I guess Ardour copy my files to the project folder, but the first part of the path seams to be missing in Fabla2?

Please let me know I theres anything I can do to further test/debug this.

**Comment by harryhaaren** [comment]
@sandsound - thanks, this is very helpful info.
Are you familiar with Jalv? See "Usage" page on OpenAV if not: http://openavproductions.com/usage/ 

Would you mind testing with Jalv, and see if it still has the same issue? Thanks!

**Comment by sandsound** [comment]
Just did a couple of quick tests with Jalv.
Loading a preset sometimes gives an empty black window and this error:
`Fabla2UI /home/sandie/.config/openAV/fabla2/fabla2.prfs : File doesn't exist, aborting.`
I don't even have a /home/sandie/.config/openAV/ folder.

And I also get this error everytime:
`transport UIvoid Fabla2::Fabla2DSP::uiMessage(int, int, int, int, float) : sample not valid! Fix this.`

btw. I can see that I have a /home/sandie/.lv2 folder in my home where it saves presets.

**Comment by harryhaaren** [comment]
The `Fabla2UI prfs` is only a configuration warning, no stress. I should mark it as that though, noted.

git pull and the 2nd "error" message will go away - I had enabled it to debug a different issue, but that's resolved now. Thanks!

**Comment by sandsound** [comment]
Just tested the latest version, and the second message is gone, but I still get a black window most of the time, this have also happened sometimes in Ardour.
In Ardour I can open the ui one or two times before this happens.

Please let me know I theres anything else you'd like me to try.

**Comment by harryhaaren** [comment]
@sandsound, thanks for the update - black window also in Jalv? I can reproduce the black-window in Ardour, but I've never experienced it in Jalv. There are some differences in the Jalv UI implementations (in terms of GCC / ABI issues, not Jalv issues) so would you test opening the Fabla2 UI with all 3 of these please? 
```
jalv.gtk
jalv.gtkmm
jalv.qt
```
Thanks, -Harry

**Comment by sandsound** [comment]
Running Fabla2 with:
`jalv.gtk http://www.openavproductions.com/fabla2`
`jalv.gtkmm http://www.openavproductions.com/fabla2`
works the first time, but closing it and running it again gives a black window, and jalv.gtkmm doesn't show the menu at all, sometimes it comes back after a few tries.
There are no errors, but I get this warning every time:
`Fabla2:State() Warning, no JSON : not loading preset.`

Using jalv.qt I get a "command not found"
I have jalv 1.4.7(svn) installed from KxStudio repros, and I guess they didn't include the qt one?

**Comment by sandsound** [comment]
btw. If you'd like, I can try out some other distro and see if the problem persists there. Is there a distro that you would recommend?

**Comment by harryhaaren** [comment]
@sandsound, thanks for the Jalv feedback. I'll take this into account, and see if I can figure out whats going on here
- the same stuff works 100% (jalv.gtk) all the time.
- Jalv.gtkmm *should not* have the menu entry that jalv.gtk does (just the way it is written)
- `Warning no JSON: not loading preset.` is expected on startup. I'll mute this
- jalv.qt, ah ok, not there, no worries.

Absolutely *no* need to swap distro - this needs to work. I might ask you to compile Jalv from source and run the same tests as above (this will 100% rule out ABI issues if it still occurs). Would you mind compiling Jalv from source?

-Harry

**Comment by sandsound** [comment]
I compiled jalv-1.4.6 from source, and I still get the black window problem.
It's not completely consistent thou, after a reboot the ui is always shown, but on second or third run, I get the black window.

Sorry if it's a dumb question, but what is ABI? Association of British Insurers? ;-)

**Comment by georgkrause** [comment]
cannot reproduce the black window issue with jalv, will check ardour crashes later.

@sandsound how is the state for you at the moment?

**Comment by sandsound** [comment]
I switched to Debian stretch to see if that would help, but unfortunately the problem is still there for me.

**Comment by harryhaaren** [comment]
Re: black screen on startup, see bullet 2 of release notes: https://drobilla.net/category/jalv/ (this may or may not be the root cause - I need to test and verify).

Re: testing with Ardour - I only test and expect F2 to (mostly) "just work" in Jalv at the moment.

**Comment by georgkrause** [comment]
@harryhaaren so you don't want issues with ardour reported?
